In [12]:
import sys, os
sys.path.append(os.path.realpath(".."))
os.environ["TF_XLA_FLAGS"]="--tf_xla_cpu_global_jit"

import util_funcs
from importlib import reload
import data_reader as read
import pandas as pd
import numpy as np
import pickle as pkl
import matplotlib.pyplot as plt
import constants
import clinical_text_analysis as cta
import tsfresh
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix, roc_curve
from os import path
import predictSeizureConvExp as psce
import keras_models.dataGen as dg
from addict import Dict
reload(psce)
from keras.utils import multi_gpu_model
import keras.optimizers
import time
from sklearn.metrics import confusion_matrix, roc_auc_score, accuracy_score, log_loss
import keras
from sklearn.metrics import accuracy_score
import keras.backend as K

In [3]:
model = keras.models.load_model("../KOEYRFDFGZWFNYSC.h5")

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [4]:
testData = pkl.load(open("/n/scratch2/ms994/standardized_simple_ensemble_test_data_patient.pkl","rb"))

In [30]:
testX, testY = testData[0]

In [6]:
testX.shape, testY.shape

((32, 21, 500, 1), (32, 341))

In [33]:
y_pred = model.predict(testX)

In [10]:
accuracy_score(testY.argmax(1),y_pred.argmax(1))

0.0

In [43]:
K.eval(keras.metrics.top_k_categorical_accuracy(testY, y_pred,  k=2))

1.0

array([248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248,
       248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248,
       248, 248, 248, 248, 248, 248])

In [22]:
y_pred.argmax(1)

array([203, 223, 207, 207, 203, 207,  69, 223, 205, 203, 229, 203, 229,
       203, 203, 203, 203, 203, 213,  69, 213, 229, 206, 229,  69, 207,
       203, 203, 299, 209, 229, 213])

In [28]:
y_pred = np.argsort(y_pred)[:,-5:]

In [ ]:
y_pred

In [18]:
testY.argmax(1)

array([248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248,
       248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248, 248,
       248, 248, 248, 248, 248, 248])